name: inorbit

services:
  web:
    container_name: inorbit_web
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - '5173:5173'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
